// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRwnC28FK1L1QTsO3MSTVD98XXkFX9GHA',
    appId: '1:808152612626:web:0ce90665c874ec9548bdcb',
    messagingSenderId: '808152612626',
    projectId: 'nomad-tiktok',
    authDomain: 'nomad-tiktok.firebaseapp.com',
    storageBucket: 'nomad-tiktok.firebasestorage.app',
    measurementId: 'G-5N78ZJYPDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnWCib90tF9ut90_fASTcZX0sAoCpIlSI',
    appId: '1:808152612626:android:085678f95f28ae2548bdcb',
    messagingSenderId: '808152612626',
    projectId: 'nomad-tiktok',
    storageBucket: 'nomad-tiktok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOVD3XBDuxxQcfbqc_2jATFZNYnN9VAW0',
    appId: '1:808152612626:ios:8380034cf70a6cfd48bdcb',
    messagingSenderId: '808152612626',
    projectId: 'nomad-tiktok',
    storageBucket: 'nomad-tiktok.firebasestorage.app',
    iosBundleId: 'com.example.tiktokclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOVD3XBDuxxQcfbqc_2jATFZNYnN9VAW0',
    appId: '1:808152612626:ios:8380034cf70a6cfd48bdcb',
    messagingSenderId: '808152612626',
    projectId: 'nomad-tiktok',
    storageBucket: 'nomad-tiktok.firebasestorage.app',
    iosBundleId: 'com.example.tiktokclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRwnC28FK1L1QTsO3MSTVD98XXkFX9GHA',
    appId: '1:808152612626:web:a477783d70bf6fa048bdcb',
    messagingSenderId: '808152612626',
    projectId: 'nomad-tiktok',
    authDomain: 'nomad-tiktok.firebaseapp.com',
    storageBucket: 'nomad-tiktok.firebasestorage.app',
    measurementId: 'G-1WK6Z9G76C',
  );

}